from django.db import models


class LecLegado(models.Model):
    """Modelo gerado automaticamente a partir do CSV - todos os campos como TextField.
    Use 'db_column' curto+único para evitar limite de 63 chars no PostgreSQL.
    """
    e_mail_do_usuario_que_realizou_o_cadastro = models.TextField(blank=True, null=True, verbose_name="e-mail_do_usuario_que_realizou_o_cadastro", db_column="e_mail_do_usuario_que_realizou_o_cadastro_22c8884b2d")
    nome_do_usuario_que_realizou_o_cadastro = models.TextField(blank=True, null=True, verbose_name="nome_do_usuario_que_realizou_o_cadastro", db_column="nome_do_usuario_que_realizou_o_cadastro_765334681d")
    nome_do_estabelecimento_solicitante = models.TextField(blank=True, null=True, verbose_name="nome_do_estabelecimento_solicitante", db_column="nome_do_estabelecimento_solicitante_820ad02cdc")
    cnes_do_estabelecimento_solicitante = models.TextField(blank=True, null=True, verbose_name="cnes_do_estabelecimento_solicitante", db_column="cnes_do_estabelecimento_solicitante_dff3c2fd8e")
    nome_do_estabelecimento_executante = models.TextField(blank=True, null=True, verbose_name="nome_do_estabelecimento_executante", db_column="nome_do_estabelecimento_executante_4419baf71d")
    cnes_do_estabelecimento_executante = models.TextField(blank=True, null=True, verbose_name="cnes_do_estabelecimento_executante", db_column="cnes_do_estabelecimento_executante_e723a54a15")
    nome_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado = models.TextField(blank=True, null=True, verbose_name="nome_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado", db_column="nome_do_paciente_utilizado_pelo_medico_para_conf_e853a7d0de")
    no_do_prontuario_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado = models.TextField(blank=True, null=True, verbose_name="no_do_prontuario_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado", db_column="no_do_prontuario_do_paciente_utilizado_pelo_medi_d19584fdf0")
    documento_do_medico_cns_ou_cpf = models.TextField(blank=True, null=True, verbose_name="documento_do_medico_cns_ou_cpf", db_column="documento_do_medico_cns_ou_cpf_47971e5ff0")
    data_de_nascimento_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado = models.TextField(blank=True, null=True, verbose_name="data_de_nascimento_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado", db_column="data_de_nascimento_do_paciente_utilizado_pelo_me_6a6409c70b")
    sexo_do_paciente = models.TextField(blank=True, null=True, verbose_name="sexo_do_paciente", db_column="sexo_do_paciente_1fd6c60065")
    racacor_do_paciente = models.TextField(blank=True, null=True, verbose_name="racacor_do_paciente", db_column="racacor_do_paciente_a6ac40fe6d")
    nome_da_mae_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado = models.TextField(blank=True, null=True, verbose_name="nome_da_mae_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado", db_column="nome_da_mae_do_paciente_utilizado_pelo_medico_pa_36b9a46299")
    telefone_de_contato_do_paciente = models.TextField(blank=True, null=True, verbose_name="telefone_de_contato_do_paciente", db_column="telefone_de_contato_do_paciente_433c3c93d0")
    nome_do_responsavel_do_paciente = models.TextField(blank=True, null=True, verbose_name="nome_do_responsavel_do_paciente", db_column="nome_do_responsavel_do_paciente_8eb4dd3bfe")
    telefone_de_contato1_do_paciente_deve_ser_preenchido_pelo_medico_ou_pelo_nir_caso_o_cadastro_do_paciente_esteja_incompleto_ou_com_numero_errado = models.TextField(blank=True, null=True, verbose_name="telefone_de_contato1_do_paciente_-_deve_ser_preenchido_pelo_medico_ou_pelo_nir_caso_o_cadastro_do_paciente_esteja_incompleto_ou_com_numero_errado", db_column="telefone_de_contato1_do_paciente_deve_ser_preenc_f75c7b789e")
    endereco_rua_no_bairro_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento = models.TextField(blank=True, null=True, verbose_name="endereco_rua_no_bairro_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento", db_column="endereco_rua_no_bairro_do_paciente_deve_ser_pree_a96ee393eb")
    municipio_de_residencia_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento = models.TextField(blank=True, null=True, verbose_name="municipio_de_residencia_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento", db_column="municipio_de_residencia_do_paciente_deve_ser_pre_e70d42ad76")
    cod_ibge_municipio_do_paciente = models.TextField(blank=True, null=True, verbose_name="cod_ibge_municipio_do_paciente", db_column="cod_ibge_municipio_do_paciente_e49a04d83f")
    unidade_federativa_do_endereco_paciente = models.TextField(blank=True, null=True, verbose_name="unidade_federativa_do_endereco_paciente", db_column="unidade_federativa_do_endereco_paciente_20b53ab8bf")
    cep_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento = models.TextField(blank=True, null=True, verbose_name="cep_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento", db_column="cep_do_paciente_deve_ser_preenchido_pelo_nir_cas_20312e32ac")
    principais_sinais_e_sintomas_clinicos_do_paciente = models.TextField(blank=True, null=True, verbose_name="principais_sinais_e_sintomas_clinicos_do_paciente", db_column="principais_sinais_e_sintomas_clinicos_do_pacient_c2ee4791c5")
    condicoes_que_justificam_a_internacao_do_paciente = models.TextField(blank=True, null=True, verbose_name="condicoes_que_justificam_a_internacao_do_paciente", db_column="condicoes_que_justificam_a_internacao_do_pacient_fa7a684c00")
    principais_resultados_de_provas_diagnosticas_resultados_de_exames_realizados_do_paciente = models.TextField(blank=True, null=True, verbose_name="principais_resultados_de_provas_diagnosticas_resultados_de_exames_realizados_do_paciente", db_column="principais_resultados_de_provas_diagnosticas_res_71eac0449d")
    diagnostico_inicial_do_paciente_que_justifica_a_necessidade_de_internacao = models.TextField(blank=True, null=True, verbose_name="diagnostico_inicial_do_paciente_que_justifica_a_necessidade_de_internacao", db_column="diagnostico_inicial_do_paciente_que_justifica_a__84a69aae98")
    cid_10_principal_do_paciente = models.TextField(blank=True, null=True, verbose_name="cid_10_principal_do_paciente", db_column="cid_10_principal_do_paciente_d7151e6b40")
    cid_10_secundario_do_paciente = models.TextField(blank=True, null=True, verbose_name="cid_10_secundario_do_paciente", db_column="cid_10_secundario_do_paciente_b73470ca98")
    cid_10_causas_associadas_do_paciente = models.TextField(blank=True, null=True, verbose_name="cid_10_causas_associadas_do_paciente", db_column="cid_10_causas_associadas_do_paciente_1f0eac0fb2")
    procedimento_indicado_pelo_medico_a_ser_realizado_no_paciente_tabela_sigtap = models.TextField(blank=True, null=True, verbose_name="procedimento_indicado_pelo_medico_a_ser_realizado_no_paciente_tabela_sigtap", db_column="procedimento_indicado_pelo_medico_a_ser_realizad_bd94093e99")
    codigo_do_procedimento_do_paciente_tabela_sigtap = models.TextField(blank=True, null=True, verbose_name="codigo_do_procedimento_do_paciente_tabela_sigtap", db_column="codigo_do_procedimento_do_paciente_tabela_sigtap_96a31a6486")
    clinica_do_paciente = models.TextField(blank=True, null=True, verbose_name="clinica_do_paciente", db_column="clinica_do_paciente_e804e701fd")
    carater_da_internacao_do_paciente = models.TextField(blank=True, null=True, verbose_name="carater_da_internacao_do_paciente", db_column="carater_da_internacao_do_paciente_3729ed01f6")
    documento_do_medico_cns_ou_cpf_1 = models.TextField(blank=True, null=True, verbose_name="documento_do_medico_cns_ou_cpf", db_column="documento_do_medico_cns_ou_cpf_1_be22920202")
    no_documento_cnscpf_do_profissional_solicitanteassistente_do_medico_essencial_para_o_faturamento = models.TextField(blank=True, null=True, verbose_name="no_documento_cnscpf_do_profissional_solicitanteassistente_do_medico_essencial_para_o_faturamento", db_column="no_documento_cnscpf_do_profissional_solicitantea_ed880b57ba")
    medico_cirurgiao_nome_do_profissional_solicitanteassistente_medico_essencial_para_o_faturamento = models.TextField(blank=True, null=True, verbose_name="medico_cirurgiao_nome_do_profissional_solicitanteassistente_medico_essencial_para_o_faturamento", db_column="medico_cirurgiao_nome_do_profissional_solicitant_f0c7ba45a8")
    data_da_solicitacao_data_do_preenchimento_pode_deixar_em_branco_para_preenchimento_posterior = models.TextField(blank=True, null=True, verbose_name="data_da_solicitacao_data_do_preenchimento_pode_deixar_em_branco_para_preenchimento_posterior", db_column="data_da_solicitacao_data_do_preenchimento_pode_d_766cb81f3a")
    etnia_do_paciente = models.TextField(blank=True, null=True, verbose_name="etnia_do_paciente", db_column="etnia_do_paciente_e24831aa3b")
    medico_cirurgiao_nome_do_profissional_solicitanteassistente_lista_suspensa_de_nomes_de_medicos_cirurgioes_cadastrados_no_aplicativo = models.TextField(blank=True, null=True, verbose_name="medico_cirurgiao_nome_do_profissional_solicitanteassistente_lista_suspensa_de_nomes_de_medicos_cirurgioes_cadastrados_no_aplicativo", db_column="medico_cirurgiao_nome_do_profissional_solicitant_969f38eee6")
    idade_do_paciente = models.TextField(blank=True, null=True, verbose_name="idade_do_paciente", db_column="idade_do_paciente_be0d4c207b")
    especialidade_do_medico_cirurgiao_especialidades_cadastradas_no_aplicativo = models.TextField(blank=True, null=True, verbose_name="especialidade_do_medico_cirurgiao_especialidades_cadastradas_no_aplicativo", db_column="especialidade_do_medico_cirurgiao_especialidades_11098b715b")
    observacao_lec_campo_aberto_para_preenchimento_no_nir = models.TextField(blank=True, null=True, verbose_name="observacao_lec_campo_aberto_para_preenchimento_no_nir", db_column="observacao_lec_campo_aberto_para_preenchimento_n_e7a4c80107")
    prioridade_clinica_0_oncologico_1_urgente_2_prioritario_3_sem_prioridade = models.TextField(blank=True, null=True, verbose_name="prioridade_clinica_0_-_oncologico_1_-_urgente_2_-_prioritario_3_-_sem_prioridade", db_column="prioridade_clinica_0_oncologico_1_urgente_2_prio_7b55353a05")
    ultimo_contato = models.TextField(blank=True, null=True, verbose_name="ultimo_contato", db_column="ultimo_contato_8c6d992e4d")
    procedimento_cirurgico_conforme_tabela_sigtap_repetido_procedimento = models.TextField(blank=True, null=True, verbose_name="procedimento_cirurgico_conforme_tabela_sigtap_repetido_procedimento", db_column="procedimento_cirurgico_conforme_tabela_sigtap_re_79bdb8d27c")
    subgrupo_sigtap_4_primeiros_algarismos_do_codigo_do_procedimento = models.TextField(blank=True, null=True, verbose_name="subgrupo_sigtap_4_primeiros_algarismos_do_codigo_do_procedimento", db_column="subgrupo_sigtap_4_primeiros_algarismos_do_codigo_51cfd83fa5")
    informa_se_o_paciente_continua_na_fila_ativa_regra_algumas_situacoes_mantem_na_fila_outras_retiram_da_fila_inativo_com_possibilidade_de_retorno_outras_retiram_da_fila_definitivamente_obito_e_etc = models.TextField(blank=True, null=True, verbose_name="informa_se_o_paciente_continua_na_fila_ativa_regra_algumas_situacoes_mantem_na_fila_outras_retiram_da_fila_inativo_com_possibilidade_de_retorno_outras_retiram_da_fila_definitivamente_obito_e_etc", db_column="informa_se_o_paciente_continua_na_fila_ativa_reg_a8fc3b4dd9")
    data_em_que_o_paciente_realizou_a_cirurgia_quando_o_status_e_cirurgia_realizada_ou_data_de_agendamento_da_cirurgia_quando_o_status_e_cirurgia_agendada = models.TextField(blank=True, null=True, verbose_name="data_em_que_o_paciente_realizou_a_cirurgia_quando_o_status_e_cirurgia_realizada_ou_data_de_agendamento_da_cirurgia_quando_o_status_e_cirurgia_agendada", db_column="data_em_que_o_paciente_realizou_a_cirurgia_quand_60b530c483")
    data_de_entrada_do_paciente_na_lec_preenchido_automaticamente_pelo_sistema_com_a_data_de_cadastro_de_novo_paciente = models.TextField(blank=True, null=True, verbose_name="data_de_entrada_do_paciente_na_lec_preenchido_automaticamente_pelo_sistema_com_a_data_de_cadastro_de_novo_paciente", db_column="data_de_entrada_do_paciente_na_lec_preenchido_au_3f773f463b")
    porte_cirurgico_porte_i_ate_2_horas_porte_ii_de_2_a_4_horas_porte_iii_de_4_a_6_horas_porte_iv_superior_a_6_horas_sem_informacao_sobre_o_porte_cirurgico = models.TextField(blank=True, null=True, verbose_name="porte_cirurgico_porte_i_-_ate_2_horas_porte_ii_-_de_2_a_4_horas_porte_iii_-_de_4_a_6_horas_porte_iv_-_superior_a_6_horas_sem_informacao_sobre_o_porte_cirurgico", db_column="porte_cirurgico_porte_i_ate_2_horas_porte_ii_de__9df25fca77")
    informa_se_ha_processo_judicial_para_a_realizacao_da_cirurgia_se_demanda_judicial_preencher_data_limite_para_realizacao_do_procedimento_e_no_do_processo_sei = models.TextField(blank=True, null=True, verbose_name="informa_se_ha_processo_judicial_para_a_realizacao_da_cirurgia_se_demanda_judicial_preencher_data_limite_para_realizacao_do_procedimento_e_no_do_processo_sei", db_column="informa_se_ha_processo_judicial_para_a_realizaca_539a18691f")
    esperatotal = models.TextField(blank=True, null=True, verbose_name="esperatotal", db_column="esperatotal_b06eb8311e")
    procedimento_2 = models.TextField(blank=True, null=True, verbose_name="procedimento_2", db_column="procedimento_2_d6800c4c97")
    subgrupo_2 = models.TextField(blank=True, null=True, verbose_name="subgrupo_2", db_column="subgrupo_2_dbf3766682")
    multipla_cirurgia = models.TextField(blank=True, null=True, verbose_name="multipla_cirurgia", db_column="multipla_cirurgia_89d11e23f6")
    sei_judicial = models.TextField(blank=True, null=True, verbose_name="sei_judicial", db_column="sei_judicial_26caa6ac3d")
    prazojudicial = models.TextField(blank=True, null=True, verbose_name="prazojudicial", db_column="prazojudicial_3da70d0e80")
    campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila = models.TextField(blank=True, null=True, verbose_name="campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila", db_column="campo_com_pequena_observacao_aparece_no_card_do__cf662d9d69")
    campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila_1 = models.TextField(blank=True, null=True, verbose_name="campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila", db_column="campo_com_pequena_observacao_aparece_no_card_do__a37ccfe222")
    quantidade_de_dias_entre_o_paciente_entrar_na_fila_data_lec_e_hoje_calculado_via_script_no_powerautomate = models.TextField(blank=True, null=True, verbose_name="quantidade_de_dias_entre_o_paciente_entrar_na_fila_data_lec_e_hoje_calculado_via_script_no_powerautomate", db_column="quantidade_de_dias_entre_o_paciente_entrar_na_fi_9341959b9e")

    def __str__(self):
        return str(self.e_mail_do_usuario_que_realizou_o_cadastro)[:120]

    class Meta:
        verbose_name = 'Lec Legado'
        verbose_name_plural = 'Lecs Legado'
