# Generated by Django 5.2.1 on 2025-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail_do_usuario_que_realizou_o_cadastro', models.TextField(blank=True, db_column='e_mail_do_usuario_que_realizou_o_cadastro_22c8884b2d', null=True, verbose_name='e-mail_do_usuario_que_realizou_o_cadastro')),
                ('nome_do_usuario_que_realizou_o_cadastro', models.TextField(blank=True, db_column='nome_do_usuario_que_realizou_o_cadastro_765334681d', null=True, verbose_name='nome_do_usuario_que_realizou_o_cadastro')),
                ('nome_do_estabelecimento_solicitante', models.TextField(blank=True, db_column='nome_do_estabelecimento_solicitante_820ad02cdc', null=True, verbose_name='nome_do_estabelecimento_solicitante')),
                ('cnes_do_estabelecimento_solicitante', models.TextField(blank=True, db_column='cnes_do_estabelecimento_solicitante_dff3c2fd8e', null=True, verbose_name='cnes_do_estabelecimento_solicitante')),
                ('nome_do_estabelecimento_executante', models.TextField(blank=True, db_column='nome_do_estabelecimento_executante_4419baf71d', null=True, verbose_name='nome_do_estabelecimento_executante')),
                ('cnes_do_estabelecimento_executante', models.TextField(blank=True, db_column='cnes_do_estabelecimento_executante_e723a54a15', null=True, verbose_name='cnes_do_estabelecimento_executante')),
                ('nome_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado', models.TextField(blank=True, db_column='nome_do_paciente_utilizado_pelo_medico_para_conf_e853a7d0de', null=True, verbose_name='nome_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado')),
                ('no_do_prontuario_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado', models.TextField(blank=True, db_column='no_do_prontuario_do_paciente_utilizado_pelo_medi_d19584fdf0', null=True, verbose_name='no_do_prontuario_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado')),
                ('documento_do_medico_cns_ou_cpf', models.TextField(blank=True, db_column='documento_do_medico_cns_ou_cpf_47971e5ff0', null=True, verbose_name='documento_do_medico_cns_ou_cpf')),
                ('data_de_nascimento_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado', models.TextField(blank=True, db_column='data_de_nascimento_do_paciente_utilizado_pelo_me_6a6409c70b', null=True, verbose_name='data_de_nascimento_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado')),
                ('sexo_do_paciente', models.TextField(blank=True, db_column='sexo_do_paciente_1fd6c60065', null=True, verbose_name='sexo_do_paciente')),
                ('racacor_do_paciente', models.TextField(blank=True, db_column='racacor_do_paciente_a6ac40fe6d', null=True, verbose_name='racacor_do_paciente')),
                ('nome_da_mae_do_paciente_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado', models.TextField(blank=True, db_column='nome_da_mae_do_paciente_utilizado_pelo_medico_pa_36b9a46299', null=True, verbose_name='nome_da_mae_do_paciente_-_utilizado_pelo_medico_para_conferencia_de_qual_paciente_esta_sendo_cadastrado')),
                ('telefone_de_contato_do_paciente', models.TextField(blank=True, db_column='telefone_de_contato_do_paciente_433c3c93d0', null=True, verbose_name='telefone_de_contato_do_paciente')),
                ('nome_do_responsavel_do_paciente', models.TextField(blank=True, db_column='nome_do_responsavel_do_paciente_8eb4dd3bfe', null=True, verbose_name='nome_do_responsavel_do_paciente')),
                ('telefone_de_contato1_do_paciente_deve_ser_preenchido_pelo_medico_ou_pelo_nir_caso_o_cadastro_do_paciente_esteja_incompleto_ou_com_numero_errado', models.TextField(blank=True, db_column='telefone_de_contato1_do_paciente_deve_ser_preenc_f75c7b789e', null=True, verbose_name='telefone_de_contato1_do_paciente_-_deve_ser_preenchido_pelo_medico_ou_pelo_nir_caso_o_cadastro_do_paciente_esteja_incompleto_ou_com_numero_errado')),
                ('endereco_rua_no_bairro_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento', models.TextField(blank=True, db_column='endereco_rua_no_bairro_do_paciente_deve_ser_pree_a96ee393eb', null=True, verbose_name='endereco_rua_no_bairro_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento')),
                ('municipio_de_residencia_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento', models.TextField(blank=True, db_column='municipio_de_residencia_do_paciente_deve_ser_pre_e70d42ad76', null=True, verbose_name='municipio_de_residencia_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento')),
                ('cod_ibge_municipio_do_paciente', models.TextField(blank=True, db_column='cod_ibge_municipio_do_paciente_e49a04d83f', null=True, verbose_name='cod_ibge_municipio_do_paciente')),
                ('unidade_federativa_do_endereco_paciente', models.TextField(blank=True, db_column='unidade_federativa_do_endereco_paciente_20b53ab8bf', null=True, verbose_name='unidade_federativa_do_endereco_paciente')),
                ('cep_do_paciente_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento', models.TextField(blank=True, db_column='cep_do_paciente_deve_ser_preenchido_pelo_nir_cas_20312e32ac', null=True, verbose_name='cep_do_paciente_-_deve_ser_preenchido_pelo_nir_caso_o_cadastro_do_paciente_essencial_para_o_faturamento')),
                ('principais_sinais_e_sintomas_clinicos_do_paciente', models.TextField(blank=True, db_column='principais_sinais_e_sintomas_clinicos_do_pacient_c2ee4791c5', null=True, verbose_name='principais_sinais_e_sintomas_clinicos_do_paciente')),
                ('condicoes_que_justificam_a_internacao_do_paciente', models.TextField(blank=True, db_column='condicoes_que_justificam_a_internacao_do_pacient_fa7a684c00', null=True, verbose_name='condicoes_que_justificam_a_internacao_do_paciente')),
                ('principais_resultados_de_provas_diagnosticas_resultados_de_exames_realizados_do_paciente', models.TextField(blank=True, db_column='principais_resultados_de_provas_diagnosticas_res_71eac0449d', null=True, verbose_name='principais_resultados_de_provas_diagnosticas_resultados_de_exames_realizados_do_paciente')),
                ('diagnostico_inicial_do_paciente_que_justifica_a_necessidade_de_internacao', models.TextField(blank=True, db_column='diagnostico_inicial_do_paciente_que_justifica_a__84a69aae98', null=True, verbose_name='diagnostico_inicial_do_paciente_que_justifica_a_necessidade_de_internacao')),
                ('cid_10_principal_do_paciente', models.TextField(blank=True, db_column='cid_10_principal_do_paciente_d7151e6b40', null=True, verbose_name='cid_10_principal_do_paciente')),
                ('cid_10_secundario_do_paciente', models.TextField(blank=True, db_column='cid_10_secundario_do_paciente_b73470ca98', null=True, verbose_name='cid_10_secundario_do_paciente')),
                ('cid_10_causas_associadas_do_paciente', models.TextField(blank=True, db_column='cid_10_causas_associadas_do_paciente_1f0eac0fb2', null=True, verbose_name='cid_10_causas_associadas_do_paciente')),
                ('procedimento_indicado_pelo_medico_a_ser_realizado_no_paciente_tabela_sigtap', models.TextField(blank=True, db_column='procedimento_indicado_pelo_medico_a_ser_realizad_bd94093e99', null=True, verbose_name='procedimento_indicado_pelo_medico_a_ser_realizado_no_paciente_tabela_sigtap')),
                ('codigo_do_procedimento_do_paciente_tabela_sigtap', models.TextField(blank=True, db_column='codigo_do_procedimento_do_paciente_tabela_sigtap_96a31a6486', null=True, verbose_name='codigo_do_procedimento_do_paciente_tabela_sigtap')),
                ('clinica_do_paciente', models.TextField(blank=True, db_column='clinica_do_paciente_e804e701fd', null=True, verbose_name='clinica_do_paciente')),
                ('carater_da_internacao_do_paciente', models.TextField(blank=True, db_column='carater_da_internacao_do_paciente_3729ed01f6', null=True, verbose_name='carater_da_internacao_do_paciente')),
                ('documento_do_medico_cns_ou_cpf_1', models.TextField(blank=True, db_column='documento_do_medico_cns_ou_cpf_1_be22920202', null=True, verbose_name='documento_do_medico_cns_ou_cpf')),
                ('no_documento_cnscpf_do_profissional_solicitanteassistente_do_medico_essencial_para_o_faturamento', models.TextField(blank=True, db_column='no_documento_cnscpf_do_profissional_solicitantea_ed880b57ba', null=True, verbose_name='no_documento_cnscpf_do_profissional_solicitanteassistente_do_medico_essencial_para_o_faturamento')),
                ('medico_cirurgiao_nome_do_profissional_solicitanteassistente_medico_essencial_para_o_faturamento', models.TextField(blank=True, db_column='medico_cirurgiao_nome_do_profissional_solicitant_f0c7ba45a8', null=True, verbose_name='medico_cirurgiao_nome_do_profissional_solicitanteassistente_medico_essencial_para_o_faturamento')),
                ('data_da_solicitacao_data_do_preenchimento_pode_deixar_em_branco_para_preenchimento_posterior', models.TextField(blank=True, db_column='data_da_solicitacao_data_do_preenchimento_pode_d_766cb81f3a', null=True, verbose_name='data_da_solicitacao_data_do_preenchimento_pode_deixar_em_branco_para_preenchimento_posterior')),
                ('etnia_do_paciente', models.TextField(blank=True, db_column='etnia_do_paciente_e24831aa3b', null=True, verbose_name='etnia_do_paciente')),
                ('medico_cirurgiao_nome_do_profissional_solicitanteassistente_lista_suspensa_de_nomes_de_medicos_cirurgioes_cadastrados_no_aplicativo', models.TextField(blank=True, db_column='medico_cirurgiao_nome_do_profissional_solicitant_969f38eee6', null=True, verbose_name='medico_cirurgiao_nome_do_profissional_solicitanteassistente_lista_suspensa_de_nomes_de_medicos_cirurgioes_cadastrados_no_aplicativo')),
                ('idade_do_paciente', models.TextField(blank=True, db_column='idade_do_paciente_be0d4c207b', null=True, verbose_name='idade_do_paciente')),
                ('especialidade_do_medico_cirurgiao_especialidades_cadastradas_no_aplicativo', models.TextField(blank=True, db_column='especialidade_do_medico_cirurgiao_especialidades_11098b715b', null=True, verbose_name='especialidade_do_medico_cirurgiao_especialidades_cadastradas_no_aplicativo')),
                ('observacao_lec_campo_aberto_para_preenchimento_no_nir', models.TextField(blank=True, db_column='observacao_lec_campo_aberto_para_preenchimento_n_e7a4c80107', null=True, verbose_name='observacao_lec_campo_aberto_para_preenchimento_no_nir')),
                ('prioridade_clinica_0_oncologico_1_urgente_2_prioritario_3_sem_prioridade', models.TextField(blank=True, db_column='prioridade_clinica_0_oncologico_1_urgente_2_prio_7b55353a05', null=True, verbose_name='prioridade_clinica_0_-_oncologico_1_-_urgente_2_-_prioritario_3_-_sem_prioridade')),
                ('ultimo_contato', models.TextField(blank=True, db_column='ultimo_contato_8c6d992e4d', null=True, verbose_name='ultimo_contato')),
                ('procedimento_cirurgico_conforme_tabela_sigtap_repetido_procedimento', models.TextField(blank=True, db_column='procedimento_cirurgico_conforme_tabela_sigtap_re_79bdb8d27c', null=True, verbose_name='procedimento_cirurgico_conforme_tabela_sigtap_repetido_procedimento')),
                ('subgrupo_sigtap_4_primeiros_algarismos_do_codigo_do_procedimento', models.TextField(blank=True, db_column='subgrupo_sigtap_4_primeiros_algarismos_do_codigo_51cfd83fa5', null=True, verbose_name='subgrupo_sigtap_4_primeiros_algarismos_do_codigo_do_procedimento')),
                ('informa_se_o_paciente_continua_na_fila_ativa_regra_algumas_situacoes_mantem_na_fila_outras_retiram_da_fila_inativo_com_possibilidade_de_retorno_outras_retiram_da_fila_definitivamente_obito_e_etc', models.TextField(blank=True, db_column='informa_se_o_paciente_continua_na_fila_ativa_reg_a8fc3b4dd9', null=True, verbose_name='informa_se_o_paciente_continua_na_fila_ativa_regra_algumas_situacoes_mantem_na_fila_outras_retiram_da_fila_inativo_com_possibilidade_de_retorno_outras_retiram_da_fila_definitivamente_obito_e_etc')),
                ('data_em_que_o_paciente_realizou_a_cirurgia_quando_o_status_e_cirurgia_realizada_ou_data_de_agendamento_da_cirurgia_quando_o_status_e_cirurgia_agendada', models.TextField(blank=True, db_column='data_em_que_o_paciente_realizou_a_cirurgia_quand_60b530c483', null=True, verbose_name='data_em_que_o_paciente_realizou_a_cirurgia_quando_o_status_e_cirurgia_realizada_ou_data_de_agendamento_da_cirurgia_quando_o_status_e_cirurgia_agendada')),
                ('data_de_entrada_do_paciente_na_lec_preenchido_automaticamente_pelo_sistema_com_a_data_de_cadastro_de_novo_paciente', models.TextField(blank=True, db_column='data_de_entrada_do_paciente_na_lec_preenchido_au_3f773f463b', null=True, verbose_name='data_de_entrada_do_paciente_na_lec_preenchido_automaticamente_pelo_sistema_com_a_data_de_cadastro_de_novo_paciente')),
                ('porte_cirurgico_porte_i_ate_2_horas_porte_ii_de_2_a_4_horas_porte_iii_de_4_a_6_horas_porte_iv_superior_a_6_horas_sem_informacao_sobre_o_porte_cirurgico', models.TextField(blank=True, db_column='porte_cirurgico_porte_i_ate_2_horas_porte_ii_de__9df25fca77', null=True, verbose_name='porte_cirurgico_porte_i_-_ate_2_horas_porte_ii_-_de_2_a_4_horas_porte_iii_-_de_4_a_6_horas_porte_iv_-_superior_a_6_horas_sem_informacao_sobre_o_porte_cirurgico')),
                ('informa_se_ha_processo_judicial_para_a_realizacao_da_cirurgia_se_demanda_judicial_preencher_data_limite_para_realizacao_do_procedimento_e_no_do_processo_sei', models.TextField(blank=True, db_column='informa_se_ha_processo_judicial_para_a_realizaca_539a18691f', null=True, verbose_name='informa_se_ha_processo_judicial_para_a_realizacao_da_cirurgia_se_demanda_judicial_preencher_data_limite_para_realizacao_do_procedimento_e_no_do_processo_sei')),
                ('esperatotal', models.TextField(blank=True, db_column='esperatotal_b06eb8311e', null=True, verbose_name='esperatotal')),
                ('procedimento_2', models.TextField(blank=True, db_column='procedimento_2_d6800c4c97', null=True, verbose_name='procedimento_2')),
                ('subgrupo_2', models.TextField(blank=True, db_column='subgrupo_2_dbf3766682', null=True, verbose_name='subgrupo_2')),
                ('multipla_cirurgia', models.TextField(blank=True, db_column='multipla_cirurgia_89d11e23f6', null=True, verbose_name='multipla_cirurgia')),
                ('sei_judicial', models.TextField(blank=True, db_column='sei_judicial_26caa6ac3d', null=True, verbose_name='sei_judicial')),
                ('prazojudicial', models.TextField(blank=True, db_column='prazojudicial_3da70d0e80', null=True, verbose_name='prazojudicial')),
                ('campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila', models.TextField(blank=True, db_column='campo_com_pequena_observacao_aparece_no_card_do__cf662d9d69', null=True, verbose_name='campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila')),
                ('campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila_1', models.TextField(blank=True, db_column='campo_com_pequena_observacao_aparece_no_card_do__a37ccfe222', null=True, verbose_name='campo_com_pequena_observacao_aparece_no_card_do_paciente_na_fila')),
                ('quantidade_de_dias_entre_o_paciente_entrar_na_fila_data_lec_e_hoje_calculado_via_script_no_powerautomate', models.TextField(blank=True, db_column='quantidade_de_dias_entre_o_paciente_entrar_na_fi_9341959b9e', null=True, verbose_name='quantidade_de_dias_entre_o_paciente_entrar_na_fila_data_lec_e_hoje_calculado_via_script_no_powerautomate')),
            ],
            options={
                'verbose_name': 'Lec Legado',
                'verbose_name_plural': 'Lecs Legado',
            },
        ),
    ]
