# Generated by Django 5.2.1 on 2025-12-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_legado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leclegado',
            name='campos_faltantes',
            field=models.TextField(blank=True, help_text='Lista de campos que não foram encontrados no AGHU', null=True, verbose_name='Campos faltantes na migração'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='data_migracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da migração'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='id_fila_migrada',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID na fila migrada'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='migrado',
            field=models.BooleanField(default=False, verbose_name='Migrado para fila atual'),
        ),
    ]
