# Generated by Django 5.2.1 on 2025-12-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lec_legado', '0002_leclegado_campos_faltantes_leclegado_data_migracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leclegado',
            name='campos_faltantes',
        ),
        migrations.RemoveField(
            model_name='leclegado',
            name='data_migracao',
        ),
        migrations.RemoveField(
            model_name='leclegado',
            name='id_fila_migrada',
        ),
        migrations.RemoveField(
            model_name='leclegado',
            name='migrado',
        ),
    ]
