# Generated by Django 5.2.1 on 2025-12-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_legado', '0003_remove_leclegado_campos_faltantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leclegado',
            name='data_migracao',
            field=models.DateTimeField(blank=True, db_column='data_migracao', null=True, verbose_name='Data da Migração'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='id_fila_migrada',
            field=models.IntegerField(blank=True, db_column='id_fila_migrada', help_text='ID da entrada criada na ListaEsperaCirurgica', null=True, verbose_name='ID na Fila Migrada'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='mensagem_migracao',
            field=models.TextField(blank=True, db_column='mensagem_migracao', help_text='Detalhes sobre o resultado da migração', null=True, verbose_name='Mensagem da Migração'),
        ),
        migrations.AddField(
            model_name='leclegado',
            name='status_migracao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('parcial', 'Parcial (com falhas)'), ('erro', 'Erro')], db_column='status_migracao', default='pendente', max_length=20, verbose_name='Status da Migração'),
        ),
    ]
