# Generated by Django 5.2.1 on 2025-10-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AihSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento_solicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Estabelecimento Solicitante')),
                ('cnes_solicitante', models.CharField(blank=True, max_length=7, null=True, verbose_name='CNES Solicitante')),
                ('nome_estabelecimento_executante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Estabelecimento Executante')),
                ('cnes_executante', models.CharField(blank=True, max_length=7, null=True, verbose_name='CNES Executante')),
                ('nome_paciente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Paciente')),
                ('numero_prontuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº do Prontuário')),
                ('cartao_nacional_saude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('raca_cor', models.CharField(blank=True, choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('AM', 'Amarela'), ('IN', 'Indígena'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Raça/Cor')),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('telefone_contato_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato 1')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável')),
                ('telefone_contato_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato 2')),
                ('endereco_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço (Rua, Nº, Bairro)')),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município de Residência')),
                ('codigo_ibge_municipio', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cód. IBGE Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('principais_sinais_sintomas', models.TextField(blank=True, null=True, verbose_name='Principais Sinais e Sintomas Clínicos')),
                ('condicoes_justificam_internacao', models.TextField(blank=True, null=True, verbose_name='Condições que Justificam a Internação')),
                ('resultados_provas_diagnosticas', models.TextField(blank=True, null=True, verbose_name='Principais Resultados de Provas Diagnósticas')),
                ('diagnostico_inicial', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Inicial')),
                ('cid10_principal', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Principal')),
                ('cid10_secundario', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Secundário')),
                ('cid10_causas_associadas', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Causas Associadas')),
                ('descricao_procedimento_solicitado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Procedimento Solicitado')),
                ('codigo_procedimento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código do Procedimento')),
                ('clinica', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clínica')),
                ('carater_internacao', models.CharField(blank=True, choices=[('E', 'Eletivo'), ('U', 'Urgência')], max_length=1, null=True, verbose_name='Caráter da Internação')),
                ('tipo_documento_profissional', models.CharField(blank=True, choices=[('CNS', 'CNS'), ('CPF', 'CPF')], max_length=3, null=True, verbose_name='Tipo Documento Profissional Solicitante')),
                ('numero_documento_profissional', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº Documento Profissional Solicitante')),
                ('nome_profissional_solicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Profissional Solicitante/Assistente')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data da Solicitação')),
                ('acidente_transito', models.BooleanField(blank=True, null=True, verbose_name='Acidente de Trânsito')),
                ('acidente_trabalho_tipico', models.BooleanField(blank=True, null=True, verbose_name='Acidente Trabalho Típico')),
                ('acidente_trabalho_trajeto', models.BooleanField(blank=True, null=True, verbose_name='Acidente Trabalho Trajeto')),
                ('cnpj_seguradora', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ da Seguradora')),
                ('numero_bilhete', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº do Bilhete')),
                ('serie_bilhete', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('cnpj_empresa', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Empresa')),
                ('cnae_empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='CNAE da Empresa')),
                ('cbor', models.CharField(blank=True, max_length=10, null=True, verbose_name='CBOR')),
                ('vinculo_previdencia', models.CharField(blank=True, choices=[('EMPREGADO', 'Empregado'), ('EMPREGADOR', 'Empregador'), ('AUTONOMO', 'Autônomo'), ('DESEMPREGADO', 'Desempregado'), ('APOSENTADO', 'Aposentado'), ('NAO_SEGURADO', 'Não Segurado')], max_length=15, null=True, verbose_name='Vínculo com a Previdência')),
                ('nome_profissional_autorizador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Profissional Autorizador')),
                ('codigo_orgao_emissor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cód. Órgão Emissor')),
                ('tipo_documento_autorizador', models.CharField(blank=True, choices=[('CNS', 'CNS'), ('CPF', 'CPF')], max_length=3, null=True, verbose_name='Tipo Documento Profissional Autorizador')),
                ('numero_documento_autorizador', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº Documento Profissional Autorizador')),
                ('data_autorizacao', models.DateField(blank=True, null=True, verbose_name='Data da Autorização')),
                ('numero_aih', models.CharField(blank=True, max_length=13, null=True, verbose_name='Nº da Autorização de Internação Hospitalar')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação/Autorização de AIH',
                'verbose_name_plural': 'Solicitações/Autorizações de AIH',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
