# Generated by Django 5.2.1 on 2025-10-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aih', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aihsolicitacao',
            name='carater_internacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Caráter da Internação'),
        ),
        migrations.AlterField(
            model_name='aihsolicitacao',
            name='tipo_documento_autorizador',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Documento Profissional Autorizador'),
        ),
        migrations.AlterField(
            model_name='aihsolicitacao',
            name='tipo_documento_profissional',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Documento Profissional Solicitante'),
        ),
        migrations.AlterField(
            model_name='aihsolicitacao',
            name='vinculo_previdencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vínculo com a Previdência'),
        ),
    ]
