# Generated by Django 5.2.1 on 2025-10-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aih', '0002_alter_aihsolicitacao_carater_internacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihsolicitacao',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Prioridade'), ('SEM', 'Sem Prioridade')], default='SEM', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='aihsolicitacao',
            name='prioridade_justificativa',
            field=models.TextField(blank=True, help_text='Motivo pelo qual o paciente recebeu a prioridade informada.', null=True, verbose_name='Justificativa da Prioridade'),
        ),
    ]
