# Generated by Django 5.2.1 on 2025-10-23 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aih', '0003_aihsolicitacao_prioridade_and_more'),
        ('fila_cirurgica', '0009_historicallistaesperacirurgica_prioridade_justificativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihsolicitacao',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aih_solicitacoes', to='fila_cirurgica.especialidadeaghu', verbose_name='Especialidade (Objeto)'),
        ),
        migrations.AddField(
            model_name='aihsolicitacao',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aih_solicitacoes_solicitadas', to='fila_cirurgica.profissionalaghu', verbose_name='Médico Solicitante (Objeto)'),
        ),
        migrations.AddField(
            model_name='aihsolicitacao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aih_solicitacoes', to='fila_cirurgica.pacienteaghu', verbose_name='Paciente (Objeto)'),
        ),
        migrations.AddField(
            model_name='aihsolicitacao',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aih_solicitacoes', to='fila_cirurgica.procedimentoaghu', verbose_name='Procedimento (Objeto)'),
        ),
    ]
