# Generated by Django 5.2.1 on 2025-10-24 17:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aih', '0004_aihsolicitacao_especialidade_aihsolicitacao_medico_and_more'),
        ('fila_cirurgica', '0009_historicallistaesperacirurgica_prioridade_justificativa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAihSolicitacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome_estabelecimento_solicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Estabelecimento Solicitante')),
                ('cnes_solicitante', models.CharField(blank=True, max_length=7, null=True, verbose_name='CNES Solicitante')),
                ('nome_estabelecimento_executante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Estabelecimento Executante')),
                ('cnes_executante', models.CharField(blank=True, max_length=7, null=True, verbose_name='CNES Executante')),
                ('nome_paciente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Paciente')),
                ('numero_prontuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº do Prontuário')),
                ('cartao_nacional_saude', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cartão Nacional de Saúde (CNS)')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('raca_cor', models.CharField(blank=True, choices=[('BR', 'Branca'), ('PR', 'Preta'), ('PA', 'Parda'), ('AM', 'Amarela'), ('IN', 'Indígena'), ('NI', 'Não Informado')], max_length=2, null=True, verbose_name='Raça/Cor')),
                ('nome_mae', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('telefone_contato_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato 1')),
                ('nome_responsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável')),
                ('telefone_contato_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato 2')),
                ('endereco_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço (Rua, Nº, Bairro)')),
                ('municipio_residencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município de Residência')),
                ('codigo_ibge_municipio', models.CharField(blank=True, max_length=7, null=True, verbose_name='Cód. IBGE Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('principais_sinais_sintomas', models.TextField(blank=True, null=True, verbose_name='Principais Sinais e Sintomas Clínicos')),
                ('condicoes_justificam_internacao', models.TextField(blank=True, null=True, verbose_name='Condições que Justificam a Internação')),
                ('resultados_provas_diagnosticas', models.TextField(blank=True, null=True, verbose_name='Principais Resultados de Provas Diagnósticas')),
                ('diagnostico_inicial', models.TextField(blank=True, null=True, verbose_name='Diagnóstico Inicial')),
                ('cid10_principal', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Principal')),
                ('cid10_secundario', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Secundário')),
                ('cid10_causas_associadas', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID 10 Causas Associadas')),
                ('descricao_procedimento_solicitado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Procedimento Solicitado')),
                ('codigo_procedimento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código do Procedimento')),
                ('clinica', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clínica')),
                ('carater_internacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Caráter da Internação')),
                ('tipo_documento_profissional', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Documento Profissional Solicitante')),
                ('numero_documento_profissional', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº Documento Profissional Solicitante')),
                ('nome_profissional_solicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Profissional Solicitante/Assistente')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data da Solicitação')),
                ('acidente_transito', models.BooleanField(blank=True, null=True, verbose_name='Acidente de Trânsito')),
                ('acidente_trabalho_tipico', models.BooleanField(blank=True, null=True, verbose_name='Acidente Trabalho Típico')),
                ('acidente_trabalho_trajeto', models.BooleanField(blank=True, null=True, verbose_name='Acidente Trabalho Trajeto')),
                ('cnpj_seguradora', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ da Seguradora')),
                ('numero_bilhete', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº do Bilhete')),
                ('serie_bilhete', models.CharField(blank=True, max_length=10, null=True, verbose_name='Série')),
                ('cnpj_empresa', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ Empresa')),
                ('cnae_empresa', models.CharField(blank=True, max_length=10, null=True, verbose_name='CNAE da Empresa')),
                ('cbor', models.CharField(blank=True, max_length=10, null=True, verbose_name='CBOR')),
                ('vinculo_previdencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vínculo com a Previdência')),
                ('nome_profissional_autorizador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Profissional Autorizador')),
                ('codigo_orgao_emissor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cód. Órgão Emissor')),
                ('tipo_documento_autorizador', models.CharField(blank=True, max_length=3, null=True, verbose_name='Tipo Documento Profissional Autorizador')),
                ('numero_documento_autorizador', models.CharField(blank=True, max_length=15, null=True, verbose_name='Nº Documento Profissional Autorizador')),
                ('data_autorizacao', models.DateField(blank=True, null=True, verbose_name='Data da Autorização')),
                ('numero_aih', models.CharField(blank=True, max_length=13, null=True, verbose_name='Nº da Autorização de Internação Hospitalar')),
                ('prioridade', models.CharField(blank=True, choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Prioridade'), ('SEM', 'Sem Prioridade')], default='SEM', max_length=3, null=True)),
                ('prioridade_justificativa', models.TextField(blank=True, help_text='Motivo pelo qual o paciente recebeu a prioridade informada.', null=True, verbose_name='Justificativa da Prioridade')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidadeaghu', verbose_name='Especialidade (Objeto)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.profissionalaghu', verbose_name='Médico Solicitante (Objeto)')),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.pacienteaghu', verbose_name='Paciente (Objeto)')),
                ('procedimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.procedimentoaghu', verbose_name='Procedimento (Objeto)')),
            ],
            options={
                'verbose_name': 'historical Solicitação/Autorização de AIH',
                'verbose_name_plural': 'historical Solicitações/Autorizações de AIH',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
