# Generated by Django 5.2.1 on 2025-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aih', '0005_historicalaihsolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aihsolicitacao',
            name='cadastrado_na_fila',
            field=models.BooleanField(default=False, help_text="Marca 'Verdadeiro' quando esta AIH é usada para criar uma entrada na fila.", verbose_name='Cadastrado na Fila?'),
        ),
        migrations.AddField(
            model_name='historicalaihsolicitacao',
            name='cadastrado_na_fila',
            field=models.BooleanField(default=False, help_text="Marca 'Verdadeiro' quando esta AIH é usada para criar uma entrada na fila.", verbose_name='Cadastrado na Fila?'),
        ),
    ]
