# Generated by Django 5.2.3 on 2025-06-18 17:28

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadeAghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_especialidade', models.CharField(max_length=10, unique=True)),
                ('nome_especialidade', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='PacienteAghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prontuario', models.CharField(max_length=20, unique=True, verbose_name='Prontuário do Paciente')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Paciente')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoAghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do Procedimento')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='ProfissionalAghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='ListaEsperaCirurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Prioridade'), ('SEM', 'Sem Prioridade')], default='SEM', max_length=3)),
                ('medida_judicial', models.BooleanField(default=False, null=True, verbose_name='Medida Judicial')),
                ('situacao', models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('data_novo_contato', models.DateField(blank=True, null=True, verbose_name='Data para novo contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo na fila?')),
                ('motivo_saida', models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.especialidadeaghu')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.pacienteaghu')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.procedimentoaghu')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.profissionalaghu', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Lista de Espera Cirúrgica',
                'verbose_name_plural': 'Lista de Espera Cirúrgica',
            },
        ),
        migrations.CreateModel(
            name='IndicadorEspecialidade',
            fields=[
            ],
            options={
                'verbose_name': 'Indicadores de Especialidades',
                'verbose_name_plural': 'Indicadores de Especialidades',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fila_cirurgica.listaesperacirurgica',),
        ),
        migrations.CreateModel(
            name='HistoricalListaEsperaCirurgica',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da alteração')),
                ('data_entrada', models.DateTimeField(blank=True, editable=False)),
                ('prioridade', models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Prioridade'), ('SEM', 'Sem Prioridade')], default='SEM', max_length=3)),
                ('medida_judicial', models.BooleanField(default=False, null=True, verbose_name='Medida Judicial')),
                ('situacao', models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('data_novo_contato', models.DateField(blank=True, null=True, verbose_name='Data para novo contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo na fila?')),
                ('motivo_saida', models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidadeaghu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.pacienteaghu')),
                ('procedimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.procedimentoaghu')),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.profissionalaghu', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Histórico de Lista de Espera Cirúrgica',
                'verbose_name_plural': 'historical Lista de Espera Cirúrgica',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicadorEspecialidade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_change_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da alteração')),
                ('data_entrada', models.DateTimeField(blank=True, editable=False)),
                ('prioridade', models.CharField(choices=[('ONC', 'Paciente Oncológico'), ('BRE', 'Com Prioridade'), ('SEM', 'Sem Prioridade')], default='SEM', max_length=3)),
                ('medida_judicial', models.BooleanField(default=False, null=True, verbose_name='Medida Judicial')),
                ('situacao', models.CharField(choices=[('CA', 'CONSULTA AGENDADA'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CNR', 'CONTATO NÃO REALIZADO'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('data_novo_contato', models.DateField(blank=True, null=True, verbose_name='Data para novo contato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Está ativo na fila?')),
                ('motivo_saida', models.CharField(blank=True, choices=[('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('especialidade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidadeaghu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.pacienteaghu')),
                ('procedimento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.procedimentoaghu')),
                ('medico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.profissionalaghu', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Histórico de Lista de Espera Cirúrgica',
                'verbose_name_plural': 'historical Indicadores de Especialidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
