# Generated by Django 5.2.1 on 2025-07-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadorespecialidade',
            name='history_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da alteraçãoxfcxdfs'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='history_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da alteraçãoxfcxdfs'),
        ),
    ]
