# Generated by Django 5.2.1 on 2025-08-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0003_alter_historicallistaesperacirurgica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidadeaghu',
            name='cod_especialidade',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código da Especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidadeaghu',
            name='nome_especialidade',
            field=models.CharField(max_length=255, verbose_name='Nome da Especialidade'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.profissionalaghu', verbose_name='médico'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fila_cirurgica.profissionalaghu', verbose_name='médico'),
        ),
        migrations.AlterField(
            model_name='profissionalaghu',
            name='matricula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Matrícula do Profissional'),
        ),
        migrations.AlterField(
            model_name='profissionalaghu',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Profissional'),
        ),
    ]
