# Generated by Django 5.2.1 on 2025-08-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0004_alter_especialidadeaghu_cod_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallistaesperacirurgica',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Entrada da Lista de Espera Cirúrgica', 'verbose_name_plural': 'historical Entradas da Lista de Espera Cirúrgica'},
        ),
        migrations.AlterModelOptions(
            name='listaesperacirurgica',
            options={'verbose_name': 'Entrada da Lista de Espera Cirúrgica', 'verbose_name_plural': 'Entradas da Lista de Espera Cirúrgica'},
        ),
    ]
