# Generated by Django 5.2.1 on 2025-10-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0005_alter_historicallistaesperacirurgica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='procedimento_secundario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.procedimentoaghu'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='procedimento_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimento_fila_secundario', to='fila_cirurgica.procedimentoaghu'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('SUCESSO', 'Cirurgia realizada no HULW'), ('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila'),
        ),
        migrations.AlterField(
            model_name='historicallistaesperacirurgica',
            name='situacao',
            field=models.CharField(choices=[('CA', 'RETORNO AGENDADO'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CA', 'CIRURGIA AGENDADA'), ('CC', 'CIRURGIA CANCELADA'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('SUCESSO', 'Cirurgia realizada no HULW'), ('MORTE', 'Paciente faleceu'), ('OUTRO_LOCAL', 'Cirurgia realizada em outro local'), ('AUTOEXCLUSAO', 'Paciente solicitou autoexclusão da fila')], max_length=20, null=True, verbose_name='Motivo da saída da fila'),
        ),
        migrations.AlterField(
            model_name='listaesperacirurgica',
            name='situacao',
            field=models.CharField(choices=[('CA', 'RETORNO AGENDADO'), ('AE', 'EXAMES PENDENTES'), ('DP', 'DOCUMENTAÇÃO PENDENTE'), ('PP', 'PACIENTE PRONTO PARA CIRURGIA'), ('CA', 'CIRURGIA AGENDADA'), ('CC', 'CIRURGIA CANCELADA'), ('T1F', 'TENTATIVA 1 FALHOU'), ('T2F', 'TENTATIVA 2 FALHOU'), ('T3F', 'TENTATIVA 3 FALHOU, NÃO SERÃO REALIZADOS NOVOS CONTATOS'), ('CRS', 'CONTATO REALIZADO COM SUCESSO')], verbose_name='Situação'),
        ),
    ]
