# Generated by Django 5.2.1 on 2025-10-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0006_historicallistaesperacirurgica_procedimento_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='especialidade_secundario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fila_cirurgica.especialidadeaghu'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='especialidade_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidade_fila_secundario', to='fila_cirurgica.especialidadeaghu'),
        ),
    ]
