# Generated by Django 5.2.1 on 2025-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0007_historicallistaesperacirurgica_especialidade_secundario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='judicial_anexos',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Anexos do Processo Judicial'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='judicial_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Medida Judicial'),
        ),
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='judicial_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo Judicial'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='judicial_anexos',
            field=models.FileField(blank=True, null=True, upload_to='anexos_judiciais/', verbose_name='Anexos do Processo Judicial'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='judicial_descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Medida Judicial'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='judicial_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Processo Judicial'),
        ),
    ]
