# Generated by Django 5.2.1 on 2025-10-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila_cirurgica', '0008_historicallistaesperacirurgica_judicial_anexos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaesperacirurgica',
            name='prioridade_justificativa',
            field=models.TextField(blank=True, help_text='Motivo pelo qual o paciente recebeu a prioridade informada.', null=True, verbose_name='Justificativa da Prioridade'),
        ),
        migrations.AddField(
            model_name='listaesperacirurgica',
            name='prioridade_justificativa',
            field=models.TextField(blank=True, help_text='Motivo pelo qual o paciente recebeu a prioridade informada.', null=True, verbose_name='Justificativa da Prioridade'),
        ),
    ]
